name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Where Am I?
        run: ls -la

      - name: Create the volume for Redis
        run: docker volume create --name=redis_data

      # - name: Build the Docker image
      # - run: |
      #     cd ServiceA/
      #     docker build -t servicea:$(date +%s) --file Dockerfile .
      # - run: |
      #     cd cd ServiceB/
      #     docker build -t serviceb:$(date +%s) --file Dockerfile .
      # - run: |
      #     cd cd ServerApp/
      #     docker build -t serverapp:$(date +%s) --file Dockerfile .

      - name: Docker compose (build images and run containers)
        run: docker-compose up -d

      - name: Other Docker commands
        run: |
          docker images
          docker ps -a
          docker network ls
          docker volume ls
